make new typo3 composer mode work
Yoast/Yoast-SEO-for-TYPO3 pull request #494
Opened 2022-04-23 11:19 UTC by zdreicom

2022-04-23 11:20 UTC, zdreicom commented
@haassie i just fix it on my own

2022-05-06 05:58 UTC, zdreicom commented
@RinyVT you are right, works fine for me too just change my pl

2022-05-11 08:47 UTC, RinyVT requested changes

2022-05-11 08:47 UTC, RinyVT commented on Classes/Utility/PathUtility.php
> +        return TYPO3PathUtility::getAbsoluteWebPath(ExtensionManagementUtility::extPath('yoast_seo')) . 'Resources/Public';
Looks like the `Resources/Public` is still outside of the `getAbsoluteWebPath` and thus will not be replaced by core?

2022-05-13 07:52 UTC, merged

2022-05-13 07:54 UTC, zdreicom commented on Classes/Utility/PathUtility.php
> +        return TYPO3PathUtility::getAbsoluteWebPath(ExtensionManagementUtility::extPath('yoast_seo') . 'Resources/Public');
@RinyVT i just check TYPO3 comments  for this method "     * Until we have a replacement for this API, the safest way to call this method is by providing absolute filesystem paths
     * and use \TYPO3\CMS\Core\Utility\PathUtility::getPublicResourceWebPath whenever possible."

I do already have a change using "getPublicResourceWebPath" witch is testst in new and old composer mode i will commit it shordly